*** Tools

**** Hugo

This static generator is used for building the main components of the website. Among the main features are:

- Editing using markdown: It uses the go programming language to 'compile' html files from markdown files.
- 'Capable Templating': I understand this as convenient code which enables users to programatically structure websites using special variables within markdown.
- Extensive selection of themes: As I already mentioned before, we will particularly focus on the academic theme.

**** Academic theme

This theme in particular focuses on academic settings like portfolios, cvs, resumes, conference websites, etc. The [[https://wowchemy.com/docs/][project]] is well documented and provides good support for academic needs. For example, the author of the theme provides a tool called [[https://pypi.org/project/academic/][Hugo Academic CLI]] which can generate publications entries from a bibtex files. 

**** [[https://ox-hugo.scripter.co][Ox-hugo]] (optional)

If you're an emacs user which likes org-mode, the ox-hugo package comes handy to organize your posts and use org files instead of markdown files.

