all: cv.pdf publications.bib

cv.pdf:
	curl -fLo cv.pdf https://raw.githubusercontent.com/typesAreSpaces/cv/main/cv.pdf

publications.bib:
	curl -fLo publications.bib https://raw.githubusercontent.com/typesAreSpaces/cv/main/publications.bib
